hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: output/${now:%Y-%m-%d-%H-%M-%S}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# Setting
mode: "inference"
checkpoint: ["./checkpoints/Transolver_299", "./checkpoints/Transolver_starccm+_299_wss"]
resume_ep: -1
log: "log"
logger_types: "tensorboard"
seed: 0
no_fabric: false  # not used
device: 0
output_dir: ${hydra:run.dir}


# Model
model: "Transolver"
space_dim: 6  # input_dim
n_layers: 5   # depth
n_hidden: 256
dropout: 0
n_head: 8
act: "gelu"
mlp_ratio: 1
fun_dim: 0
out_dim: 4
slice_num: 32
ref: 8
n_iter: 1
unified_pos: false
batch_size: 1
sdf_spatial_resolution: [64, 64, 64] # or [70, 70, 70]
reshape: False


# Run
run_name: "Transovler"
project_name: "DNNFluid-Car"


# Hyper-parameters
lr: 0.001
num_epochs: 300 # 300
n_train_num: 1 # 2772 # 2776-"0978/1034/2860/3641"
n_val_num: 1 # 595
n_test_num: 10 # 595
enable_dp: false
enable_mp: false
enable_pp: false
only_save_sdf: false
lazy_loading: true
cd_finetune: false

# DataSet
data_module: "pointcloud"
  _target_: ppcfd.data.PointCloudDataModule
  data_dir: "./data_drivaer/"
  n_train_num: 1
  n_test_num: 1

out_channels: [1,] # pressure+wss
out_keys: ["pressure",]
train_sample_number: 70000
input_filename: "test.ply"
output_filename: "test.vtk"
large_stl: false

# Physics
mass_density: 1.0
flow_speed: 30.0
simulation_type: "AeroDynamic"
